# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47f198a947fc61eaad389999ed436d9f81a0f57f3e85f2bae95c252c4ce3da5f99c5e7d1003d4db30f6bbe5663e5fa129dc76a0d848d37689cdb4c1eb76224d8

test:
  secret_key_base: 9e2cba4e7ed61afaba3973ee0dba97fe50da2adc325ce13b07855cc55a019a9ff0a2148a6f283058e30d095604e24ca0961d6a3194438d7ed61fc024121ff883

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
